// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OData.Data.DataContext;

#nullable disable

namespace OData.Data.Migrations
{
    [DbContext(typeof(ODataDbContext))]
    partial class ODataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OData.Data.Models.Gadget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gadgets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            Cost = 12000m,
                            ProductName = "Samsung Galaxy",
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            Cost = 13000m,
                            ProductName = "IPhone",
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "IBM",
                            Cost = 34999m,
                            ProductName = "IBM Thinkpad",
                            Type = "Laptop"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "HP",
                            Cost = 21000m,
                            ProductName = "HP ProBook",
                            Type = "Laptop"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Nokia",
                            Cost = 11000m,
                            ProductName = "Nokia 9222",
                            Type = "Mobile"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
